### ISSUE TITLE
(DB connection handling) Excessive cycling of DB connection

### ISSUE THREAD

**Issue by ProgrammerDan** [Pentom/modmail_ticketmanager#2] opened 2015-04-14 18:56 UTC
Just going to toss this one out here as I haven't profiled or executed the script yet, but you defined a few helper functions -- openSqlConnections and closeSqlConnections, bundling cursor creation/transaction handling/ and database connection handling in one. That's ... okay. Not great, but okay. My concern/issue is that openSqlConnections shows up pretty often, and although you wrote it to be idempotent (good), I'm wondering if you've peppered the code with the potential for new connections as a defensive measure (connection might have gone away?) or just because you didn't want to carefully monitor/manage your cursors and transactions?

In any case, a few specific suggestions: In the init() method, around [L127](https://github.com/Pentom/modmail_ticketmanager/blob/master/modmail_ticketmanager.py#L127) you commit & close the cursor/connection, only to immediately reopen it. Better to remove L127 and L128, they are spurious. 

It's not clear why you open the connection in [L154](https://github.com/Pentom/modmail_ticketmanager/blob/master/modmail_ticketmanager.py#L154), but don't leverage the connection until processModMailRootMessage -- but that method goes ahead and [calls it anyway](https://github.com/Pentom/modmail_ticketmanager/blob/master/modmail_ticketmanager.py#L251). Pick one; interior is the way to go, if you expect the reddit connections to be a bottleneck. So, remove L154 and keep L251 is my recommendation.

There are a few others, but the last two, at the end of processModMail [L215-216](https://github.com/Pentom/modmail_ticketmanager/blob/master/modmail_ticketmanager.py#L215) really threw me for a loop. They should be removable.

Ordinarily, I'd just put the above in a pull request, but again since I'm just reading the code and not testing, I figured it'd be better to give you a easy format for response in case these lines are intentional.

**Comment by Pentom** [comment] 2015-04-14 22:32
In regards to db connections, sqlite has a few fun problems with python not the least of which is that you are going to need to close your connection after ddl changes to make them persist to the sqlite file.  A lot of the things that you would never do in a traditional rdbms is just done for the sqlite.  Project wasnt big enough / important enough to require a real big boy db - sqlite will work fine as long as you understand its limitations (it 'works').  

> In any case, a few specific suggestions: In the init() method, around L127 you commit & close the cursor/connection, only to immediately reopen it. Better to remove L127 and L128, they are spurious.

This is why you see it closed/opened 127 ish between each ddl statement.  Not changing since its executed once per python script initialization and by design.

> It's not clear why you open the connection in L154, but don't leverage the connection until processModMailRootMessage -- but that method goes ahead and calls it anyway. Pick one; interior is the way to go, if you expect the reddit connections to be a bottleneck. So, remove L154 and keep L251 is my recommendation.

Refactoring work.  Take a look at V1 and you will see the surgery performed to make it a bit easier to keep up to date.  This appears to have been left from that point and I agree, it can be removed.  Will do so.

> There are a few others, but the last two, at the end of processModMail L215-216 really threw me for a loop. They should be removable.

I agree but I do wonder why that was added.  Perhaps it was from an early design when I wanted to guarantee the function would leave the sql state how it was initially (and then I gave up on doing that there)?  Will remove.  _Just looked at the code of v1, nope, this flub was from before my first check in.  I am going to blame just missing it in a refactor cycle.  Nice catch and thanks!_  \* Edit yeah found what it was meant for.  =/  Sqlite keeps the file open without persisting changes until you commit which I had tied into the closeconnection helper function.  https://docs.python.org/2/library/sqlite3.html .  Hrmph.  Lets see if I can make this a bit better and explicitly be opening/closing those guys.*

Python is not my language of choice so feel free to offer criticism if you are more familiar with it than I am.

**Comment by Pentom** [comment] 2015-04-14 23:01
Perhaps erred with more cycling of transactions but this probably results in a better product in so far as the transaction is open only for the period of time we need to access it and closed thereafter.  A possible improvement, if we find the time spent constructing/deconstructing the actual file connection is too long, would be to not open/close the sqlite db file so much but its a trade off.  Leave the connection open and a file lock is held that prohibits some file system maintenance... keep it closed except when specifically needing it and you could waste some cycles churning that.  

I think thats an OK trade for now.

Closing this issue with this change but feel free to make suggestions or set up a pull if you see something that is inappropriate for Python.  Again, not my language of choice so if this is your language then please don't hold back.

**Closed as completed by Pentom** 2015-04-14 23:01 UTC

**Comment by ProgrammerDan** [comment] 2015-04-15 14:44
Looked over the changes committed; seems better, at least from the exposed portions in the diff. A few general comments:

> not the least of which is that you are going to need to close your connection after ddl changes to make them persist to the sqlite file

This is true; but only if you have multiple applications attempting to access the same sqlite database. If it's a singlethreaded application like this, DDL, inserts, and other changes are buffered in memory and should be immediately available to the active connection. Unless you create a second connection in the same application, the DDL changes will be available to new cursors on the same connection (assuming you commit).

That said, I haven't used sqlite with python in over a year now, so things might be getting rusty or may have changed. I also must admit that I typically handled my DDL in initialization scripts as part of an install process, not opportunistically as part of the main program execution.

> A possible improvement, if we find the time spent constructing/deconstructing the actual file connection is too long, would be to not open/close the sqlite db file so much but its a trade off

This is acceptable. If the needs grow beyond SQLite, you'd typically hand this concern off to a connection pool anyway, so the "pattern" is a good one. Respecting the design of SQLite concerning its file system locking behavior sounds like the right choice to me, even if there's a little overhead from acquiring/releasing those locks.
